### ISSUE TITLE
Add option to exclude ports in range

### ISSUE THREAD

**Issue by devmaximilian** [Beyarz/portforge.cr#2]
Would it be possible to add support for excluding specific ports? I'm thinking this could be an additional argument passed to the script (a comma-delimited list of ports).

An example call could look like the following:

`portforge.cr localhost 4440 4445 4442,4443`

This would exclude ports 4442 and 4443.

The reasoning behind my feature request is that I might want to run a web server on ports 8080, 8081 and 8082. (And still use the script to make it appear as if I'm using ports 8000 - 9000)

Let me know what you think!

**Comment by Beyarz** [comment]
Being able to exclude ports is not a bad idea, what do you think of instead of using comma separated list, we had `--exclude` flag and `-e` for short?

So `portforge.cr localhost 4440 4445 4442,4443`
would instead be `portforge.cr localhost 4440 4445 --exclude 4442 4443`.
Both options work but I like the second option more.

I'll try to get this feature implemented as soon as possible, what you can do in the meantime is to start your service before you running portforge since it automatically detects the already open ports.

**Comment by devmaximilian** [comment]
I'd say the second one is definitely better.
